package com.zym.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.zym.domain.Collection;

public interface CollectionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer collectionid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection
     *
     * @mbggenerated
     */
    int insert(Collection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection
     *
     * @mbggenerated
     */
    int insertSelective(Collection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection
     *
     * @mbggenerated
     */
    Collection selectByPrimaryKey(Integer collectionid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Collection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Collection record);
    
    
    List<Collection> selectCollectionList();
    Collection selectCollectionByUseridAndLecturesid( @Param("userid") long userid, @Param("lecturesid") int lecturesid);
    List<Collection>    queryuserenrollByuserid( @Param("userid") long userid);
    List<Collection> getCollectionByDate(Map<String, Object> map);
}