package com.zym.dao;

import java.util.List;

import com.zym.domain.Colleges;

public interface CollegesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table colleges
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer collegesid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table colleges
     *
     * @mbggenerated
     */
    int insert(Colleges record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table colleges
     *
     * @mbggenerated
     */
    int insertSelective(Colleges record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table colleges
     *
     * @mbggenerated
     */
    Colleges selectByPrimaryKey(Integer collegesid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table colleges
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Colleges record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table colleges
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Colleges record);
   List<Colleges> selectCollegesList();
    
   Colleges  selectCollegesbyCollegesname(String collegesname);
}