package com.zym.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.zym.domain.Lectures;

public interface LecturesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lectures
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer lecturesid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lectures
     *
     * @mbggenerated
     */
    int insert(Lectures record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lectures
     *
     * @mbggenerated
     */
    int insertSelective(Lectures record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lectures
     *
     * @mbggenerated
     */
    Lectures selectByPrimaryKey(Integer lecturesid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lectures
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Lectures record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lectures
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Lectures record);
	List<Lectures> selectLecturesList();
	List<Lectures> selectLecturesListlike( @Param("lecturesname") String lecturesname);
	List<Lectures> lecturesQuerylikebyuserid( @Param("userid") long userid);

	List<Lectures> getLecturesInByDate(Map<String, Object> map);
}