package com.zym.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.zym.domain.SignIn;

public interface SignInMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signin
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer signinid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signin
     *
     * @mbggenerated
     */
    int insert(SignIn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signin
     *
     * @mbggenerated
     */
    int insertSelective(SignIn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signin
     *
     * @mbggenerated
     */
    SignIn selectByPrimaryKey(Integer signinid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signin
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SignIn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signin
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SignIn record);
    
     List<SignIn> selectsigninList();

	List<SignIn> getSignInByDate(Map<String, Object> map);
	
	  List<SignIn> queryuserenrollBylecturesid(@Param("lecturesid") int lecturesid);

}