package com.zym.domain;

import java.io.Serializable;
import java.util.Date;

public class SignIn implements Serializable {

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	private User user;

	public Lectures getLectures() {
		return lectures;
	}

	public void setLectures(Lectures lectures) {
		this.lectures = lectures;
	}

	private Lectures lectures;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column signin.signinid
	 *
	 * @mbggenerated
	 */
	private Integer signinid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column signin.lecturesid
	 *
	 * @mbggenerated
	 */
	private Integer lecturesid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column signin.userid
	 *
	 * @mbggenerated
	 */
	private Long userid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column signin.signintime
	 *
	 * @mbggenerated
	 */
	private Date signintime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table signin
	 *
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column signin.signinid
	 *
	 * @return the value of signin.signinid
	 *
	 * @mbggenerated
	 */
	public Integer getSigninid() {
		return signinid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column signin.signinid
	 *
	 * @param signinid
	 *            the value for signin.signinid
	 *
	 * @mbggenerated
	 */
	public void setSigninid(Integer signinid) {
		this.signinid = signinid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column signin.lecturesid
	 *
	 * @return the value of signin.lecturesid
	 *
	 * @mbggenerated
	 */
	public Integer getLecturesid() {
		return lecturesid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column signin.lecturesid
	 *
	 * @param lecturesid
	 *            the value for signin.lecturesid
	 *
	 * @mbggenerated
	 */
	public void setLecturesid(Integer lecturesid) {
		this.lecturesid = lecturesid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column signin.userid
	 *
	 * @return the value of signin.userid
	 *
	 * @mbggenerated
	 */
	public Long getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column signin.userid
	 *
	 * @param userid
	 *            the value for signin.userid
	 *
	 * @mbggenerated
	 */
	public void setUserid(Long userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column signin.signintime
	 *
	 * @return the value of signin.signintime
	 *
	 * @mbggenerated
	 */
	public Date getSignintime() {
		return signintime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column signin.signintime
	 *
	 * @param signintime
	 *            the value for signin.signintime
	 *
	 * @mbggenerated
	 */
	public void setSignintime(Date signintime) {
		this.signintime = signintime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table signin
	 *
	 * @mbggenerated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		SignIn other = (SignIn) that;
		return (this.getSigninid() == null ? other.getSigninid() == null
				: this.getSigninid().equals(other.getSigninid()))
				&& (this.getLecturesid() == null ? other.getLecturesid() == null
						: this.getLecturesid().equals(other.getLecturesid()))
				&& (this.getUserid() == null ? other.getUserid() == null : this.getUserid().equals(other.getUserid()))
				&& (this.getSignintime() == null ? other.getSignintime() == null
						: this.getSignintime().equals(other.getSignintime()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table signin
	 *
	 * @mbggenerated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getSigninid() == null) ? 0 : getSigninid().hashCode());
		result = prime * result + ((getLecturesid() == null) ? 0 : getLecturesid().hashCode());
		result = prime * result + ((getUserid() == null) ? 0 : getUserid().hashCode());
		result = prime * result + ((getSignintime() == null) ? 0 : getSignintime().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table signin
	 *
	 * @mbggenerated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", signinid=").append(signinid);
		sb.append(", lecturesid=").append(lecturesid);
		sb.append(", userid=").append(userid);
		sb.append(", signintime=").append(signintime);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}