package com.zym.domain;

import java.io.Serializable;

public class LecturesType implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lecturestype.lecturestypeid
     *
     * @mbggenerated
     */
    private Integer lecturestypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lecturestype.lecturestypename
     *
     * @mbggenerated
     */
    private String lecturestypename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lecturestype.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lecturestype
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lecturestype.lecturestypeid
     *
     * @return the value of lecturestype.lecturestypeid
     *
     * @mbggenerated
     */
    public Integer getLecturestypeid() {
        return lecturestypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lecturestype.lecturestypeid
     *
     * @param lecturestypeid the value for lecturestype.lecturestypeid
     *
     * @mbggenerated
     */
    public void setLecturestypeid(Integer lecturestypeid) {
        this.lecturestypeid = lecturestypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lecturestype.lecturestypename
     *
     * @return the value of lecturestype.lecturestypename
     *
     * @mbggenerated
     */
    public String getLecturestypename() {
        return lecturestypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lecturestype.lecturestypename
     *
     * @param lecturestypename the value for lecturestype.lecturestypename
     *
     * @mbggenerated
     */
    public void setLecturestypename(String lecturestypename) {
        this.lecturestypename = lecturestypename == null ? null : lecturestypename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lecturestype.description
     *
     * @return the value of lecturestype.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lecturestype.description
     *
     * @param description the value for lecturestype.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lecturestype
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        LecturesType other = (LecturesType) that;
        return (this.getLecturestypeid() == null ? other.getLecturestypeid() == null : this.getLecturestypeid().equals(other.getLecturestypeid()))
            && (this.getLecturestypename() == null ? other.getLecturestypename() == null : this.getLecturestypename().equals(other.getLecturestypename()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lecturestype
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getLecturestypeid() == null) ? 0 : getLecturestypeid().hashCode());
        result = prime * result + ((getLecturestypename() == null) ? 0 : getLecturestypename().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lecturestype
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", lecturestypeid=").append(lecturestypeid);
        sb.append(", lecturestypename=").append(lecturestypename);
        sb.append(", description=").append(description);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}