package com.zym.dao;

import java.util.List;

import com.zym.domain.Classroom;

public interface ClassroomMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer classroomid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom
     *
     * @mbggenerated
     */
    int insert(Classroom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom
     *
     * @mbggenerated
     */
    int insertSelective(Classroom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom
     *
     * @mbggenerated
     */
    Classroom selectByPrimaryKey(Integer classroomid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Classroom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Classroom record);
    
    List<Classroom> selectClassroomList();
    
    Classroom  selectClassroombyClassroomname(String classroomname);
    
}