package com.zym.domain;

import java.io.Serializable;
import java.util.Date;

public class Lectures implements Serializable {
	Classroom classroom;
	public Classroom getClassroom() {
		return classroom;
	}
	public void setClassroom(Classroom classroom) {
		this.classroom = classroom;
	}

	Colleges colleges;

	public Colleges getColleges() {
		return colleges;
	}

	public void setColleges(Colleges colleges) {
		this.colleges = colleges;
	}

	LecturesType lecturesType;

	public LecturesType getLecturesType() {
		return lecturesType;
	}

	public void setLecturesType(LecturesType lecturesType) {
		this.lecturesType = lecturesType;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column lectures.lecturesid
	 *
	 * @mbggenerated
	 */
	private Integer lecturesid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column lectures.lecturesname
	 *
	 * @mbggenerated
	 */
	private String lecturesname;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column lectures.speechmaker
	 *
	 * @mbggenerated
	 */
	private String speechmaker;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column lectures.lecturestype
	 *
	 * @mbggenerated
	 */
	private Integer lecturestype;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column lectures.collegesid
	 *
	 * @mbggenerated
	 */
	private Integer collegesid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column lectures.Registrationtype
	 *
	 * @mbggenerated
	 */
	private Integer registrationtype;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column lectures.lecturescontent
	 *
	 * @mbggenerated
	 */
	private String lecturescontent;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column lectures.papeview
	 *
	 * @mbggenerated
	 */
	private Long papeview;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column lectures.enrollnumber
	 *
	 * @mbggenerated
	 */
	private Integer enrollnumber;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column lectures.addtime
	 *
	 * @mbggenerated
	 */
	private Date addtime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column lectures.lecturestime
	 *
	 * @mbggenerated
	 */
	private Date lecturestime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column lectures.poster
	 *
	 * @mbggenerated
	 */
	private String poster;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column lectures.classroomid
	 *
	 * @mbggenerated
	 */
	private String classroomid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column lectures.stats
	 *
	 * @mbggenerated
	 */
	private Integer stats;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table lectures
	 *
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column lectures.lecturesid
	 *
	 * @return the value of lectures.lecturesid
	 *
	 * @mbggenerated
	 */
	public Integer getLecturesid() {
		return lecturesid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column lectures.lecturesid
	 *
	 * @param lecturesid
	 *            the value for lectures.lecturesid
	 *
	 * @mbggenerated
	 */
	public void setLecturesid(Integer lecturesid) {
		this.lecturesid = lecturesid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column lectures.lecturesname
	 *
	 * @return the value of lectures.lecturesname
	 *
	 * @mbggenerated
	 */
	public String getLecturesname() {
		return lecturesname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column lectures.lecturesname
	 *
	 * @param lecturesname
	 *            the value for lectures.lecturesname
	 *
	 * @mbggenerated
	 */
	public void setLecturesname(String lecturesname) {
		this.lecturesname = lecturesname == null ? null : lecturesname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column lectures.speechmaker
	 *
	 * @return the value of lectures.speechmaker
	 *
	 * @mbggenerated
	 */
	public String getSpeechmaker() {
		return speechmaker;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column lectures.speechmaker
	 *
	 * @param speechmaker
	 *            the value for lectures.speechmaker
	 *
	 * @mbggenerated
	 */
	public void setSpeechmaker(String speechmaker) {
		this.speechmaker = speechmaker == null ? null : speechmaker.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column lectures.lecturestype
	 *
	 * @return the value of lectures.lecturestype
	 *
	 * @mbggenerated
	 */
	public Integer getLecturestype() {
		return lecturestype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column lectures.lecturestype
	 *
	 * @param lecturestype
	 *            the value for lectures.lecturestype
	 *
	 * @mbggenerated
	 */
	public void setLecturestype(Integer lecturestype) {
		this.lecturestype = lecturestype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column lectures.collegesid
	 *
	 * @return the value of lectures.collegesid
	 *
	 * @mbggenerated
	 */
	public Integer getCollegesid() {
		return collegesid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column lectures.collegesid
	 *
	 * @param collegesid
	 *            the value for lectures.collegesid
	 *
	 * @mbggenerated
	 */
	public void setCollegesid(Integer collegesid) {
		this.collegesid = collegesid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column lectures.Registrationtype
	 *
	 * @return the value of lectures.Registrationtype
	 *
	 * @mbggenerated
	 */
	public Integer getRegistrationtype() {
		return registrationtype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column lectures.Registrationtype
	 *
	 * @param registrationtype
	 *            the value for lectures.Registrationtype
	 *
	 * @mbggenerated
	 */
	public void setRegistrationtype(Integer registrationtype) {
		this.registrationtype = registrationtype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column lectures.lecturescontent
	 *
	 * @return the value of lectures.lecturescontent
	 *
	 * @mbggenerated
	 */
	public String getLecturescontent() {
		return lecturescontent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column lectures.lecturescontent
	 *
	 * @param lecturescontent
	 *            the value for lectures.lecturescontent
	 *
	 * @mbggenerated
	 */
	public void setLecturescontent(String lecturescontent) {
		this.lecturescontent = lecturescontent == null ? null : lecturescontent.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column lectures.papeview
	 *
	 * @return the value of lectures.papeview
	 *
	 * @mbggenerated
	 */
	public Long getPapeview() {
		return papeview;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column lectures.papeview
	 *
	 * @param papeview
	 *            the value for lectures.papeview
	 *
	 * @mbggenerated
	 */
	public void setPapeview(Long papeview) {
		this.papeview = papeview;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column lectures.enrollnumber
	 *
	 * @return the value of lectures.enrollnumber
	 *
	 * @mbggenerated
	 */
	public Integer getEnrollnumber() {
		return enrollnumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column lectures.enrollnumber
	 *
	 * @param enrollnumber
	 *            the value for lectures.enrollnumber
	 *
	 * @mbggenerated
	 */
	public void setEnrollnumber(Integer enrollnumber) {
		this.enrollnumber = enrollnumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column lectures.addtime
	 *
	 * @return the value of lectures.addtime
	 *
	 * @mbggenerated
	 */
	public Date getAddtime() {
		return addtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column lectures.addtime
	 *
	 * @param addtime
	 *            the value for lectures.addtime
	 *
	 * @mbggenerated
	 */
	public void setAddtime(Date addtime) {
		this.addtime = addtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column lectures.lecturestime
	 *
	 * @return the value of lectures.lecturestime
	 *
	 * @mbggenerated
	 */
	public Date getLecturestime() {
		return lecturestime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column lectures.lecturestime
	 *
	 * @param lecturestime
	 *            the value for lectures.lecturestime
	 *
	 * @mbggenerated
	 */
	public void setLecturestime(Date lecturestime) {
		this.lecturestime = lecturestime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column lectures.poster
	 *
	 * @return the value of lectures.poster
	 *
	 * @mbggenerated
	 */
	public String getPoster() {
		return poster;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column lectures.poster
	 *
	 * @param poster
	 *            the value for lectures.poster
	 *
	 * @mbggenerated
	 */
	public void setPoster(String poster) {
		this.poster = poster == null ? null : poster.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column lectures.classroomid
	 *
	 * @return the value of lectures.classroomid
	 *
	 * @mbggenerated
	 */
	public String getClassroomid() {
		return classroomid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column lectures.classroomid
	 *
	 * @param classroomid
	 *            the value for lectures.classroomid
	 *
	 * @mbggenerated
	 */
	public void setClassroomid(String classroomid) {
		this.classroomid = classroomid == null ? null : classroomid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column lectures.stats
	 *
	 * @return the value of lectures.stats
	 *
	 * @mbggenerated
	 */
	public Integer getStats() {
		return stats;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column lectures.stats
	 *
	 * @param stats
	 *            the value for lectures.stats
	 *
	 * @mbggenerated
	 */
	public void setStats(Integer stats) {
		this.stats = stats;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table lectures
	 *
	 * @mbggenerated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		Lectures other = (Lectures) that;
		return (this.getLecturesid() == null ? other.getLecturesid() == null
				: this.getLecturesid().equals(other.getLecturesid()))
				&& (this.getLecturesname() == null ? other.getLecturesname() == null
						: this.getLecturesname().equals(other.getLecturesname()))
				&& (this.getSpeechmaker() == null ? other.getSpeechmaker() == null
						: this.getSpeechmaker().equals(other.getSpeechmaker()))
				&& (this.getLecturestype() == null ? other.getLecturestype() == null
						: this.getLecturestype().equals(other.getLecturestype()))
				&& (this.getCollegesid() == null ? other.getCollegesid() == null
						: this.getCollegesid().equals(other.getCollegesid()))
				&& (this.getRegistrationtype() == null ? other.getRegistrationtype() == null
						: this.getRegistrationtype().equals(other.getRegistrationtype()))
				&& (this.getLecturescontent() == null ? other.getLecturescontent() == null
						: this.getLecturescontent().equals(other.getLecturescontent()))
				&& (this.getPapeview() == null ? other.getPapeview() == null
						: this.getPapeview().equals(other.getPapeview()))
				&& (this.getEnrollnumber() == null ? other.getEnrollnumber() == null
						: this.getEnrollnumber().equals(other.getEnrollnumber()))
				&& (this.getAddtime() == null ? other.getAddtime() == null
						: this.getAddtime().equals(other.getAddtime()))
				&& (this.getLecturestime() == null ? other.getLecturestime() == null
						: this.getLecturestime().equals(other.getLecturestime()))
				&& (this.getPoster() == null ? other.getPoster() == null : this.getPoster().equals(other.getPoster()))
				&& (this.getClassroomid() == null ? other.getClassroomid() == null
						: this.getClassroomid().equals(other.getClassroomid()))
				&& (this.getStats() == null ? other.getStats() == null : this.getStats().equals(other.getStats()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table lectures
	 *
	 * @mbggenerated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getLecturesid() == null) ? 0 : getLecturesid().hashCode());
		result = prime * result + ((getLecturesname() == null) ? 0 : getLecturesname().hashCode());
		result = prime * result + ((getSpeechmaker() == null) ? 0 : getSpeechmaker().hashCode());
		result = prime * result + ((getLecturestype() == null) ? 0 : getLecturestype().hashCode());
		result = prime * result + ((getCollegesid() == null) ? 0 : getCollegesid().hashCode());
		result = prime * result + ((getRegistrationtype() == null) ? 0 : getRegistrationtype().hashCode());
		result = prime * result + ((getLecturescontent() == null) ? 0 : getLecturescontent().hashCode());
		result = prime * result + ((getPapeview() == null) ? 0 : getPapeview().hashCode());
		result = prime * result + ((getEnrollnumber() == null) ? 0 : getEnrollnumber().hashCode());
		result = prime * result + ((getAddtime() == null) ? 0 : getAddtime().hashCode());
		result = prime * result + ((getLecturestime() == null) ? 0 : getLecturestime().hashCode());
		result = prime * result + ((getPoster() == null) ? 0 : getPoster().hashCode());
		result = prime * result + ((getClassroomid() == null) ? 0 : getClassroomid().hashCode());
		result = prime * result + ((getStats() == null) ? 0 : getStats().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table lectures
	 *
	 * @mbggenerated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", lecturesid=").append(lecturesid);
		sb.append(", lecturesname=").append(lecturesname);
		sb.append(", speechmaker=").append(speechmaker);
		sb.append(", lecturestype=").append(lecturestype);
		sb.append(", collegesid=").append(collegesid);
		sb.append(", registrationtype=").append(registrationtype);
		sb.append(", lecturescontent=").append(lecturescontent);
		sb.append(", papeview=").append(papeview);
		sb.append(", enrollnumber=").append(enrollnumber);
		sb.append(", addtime=").append(addtime);
		sb.append(", lecturestime=").append(lecturestime);
		sb.append(", poster=").append(poster);
		sb.append(", classroomid=").append(classroomid);
		sb.append(", stats=").append(stats);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}