package com.zym.domain;

import java.io.Serializable;
import java.util.Date;

public class Comment implements Serializable {
   
	private User user;
    public User getUser() {
		return user;
	}
    public Lectures getLectures() {
		return lectures;
	}

	public void setLectures(Lectures lectures) {
		this.lectures = lectures;
	}
	private Lectures lectures;
  
	public void setUser(User user) {
		this.user = user;
	}
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.commentid
     *
     * @mbggenerated
     */
    private Integer commentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.userid
     *
     * @mbggenerated
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.lecturesid
     *
     * @mbggenerated
     */
    private Integer lecturesid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.commentcontent
     *
     * @mbggenerated
     */
    private String commentcontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.conmmentdate
     *
     * @mbggenerated
     */
    private Date conmmentdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table comment
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.commentid
     *
     * @return the value of comment.commentid
     *
     * @mbggenerated
     */
    public Integer getCommentid() {
        return commentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.commentid
     *
     * @param commentid the value for comment.commentid
     *
     * @mbggenerated
     */
    public void setCommentid(Integer commentid) {
        this.commentid = commentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.userid
     *
     * @return the value of comment.userid
     *
     * @mbggenerated
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.userid
     *
     * @param userid the value for comment.userid
     *
     * @mbggenerated
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.lecturesid
     *
     * @return the value of comment.lecturesid
     *
     * @mbggenerated
     */
    public Integer getLecturesid() {
        return lecturesid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.lecturesid
     *
     * @param lecturesid the value for comment.lecturesid
     *
     * @mbggenerated
     */
    public void setLecturesid(Integer lecturesid) {
        this.lecturesid = lecturesid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.commentcontent
     *
     * @return the value of comment.commentcontent
     *
     * @mbggenerated
     */
    public String getCommentcontent() {
        return commentcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.commentcontent
     *
     * @param commentcontent the value for comment.commentcontent
     *
     * @mbggenerated
     */
    public void setCommentcontent(String commentcontent) {
        this.commentcontent = commentcontent == null ? null : commentcontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.conmmentdate
     *
     * @return the value of comment.conmmentdate
     *
     * @mbggenerated
     */
    public Date getConmmentdate() {
        return conmmentdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.conmmentdate
     *
     * @param conmmentdate the value for comment.conmmentdate
     *
     * @mbggenerated
     */
    public void setConmmentdate(Date conmmentdate) {
        this.conmmentdate = conmmentdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Comment other = (Comment) that;
        return (this.getCommentid() == null ? other.getCommentid() == null : this.getCommentid().equals(other.getCommentid()))
            && (this.getUserid() == null ? other.getUserid() == null : this.getUserid().equals(other.getUserid()))
            && (this.getLecturesid() == null ? other.getLecturesid() == null : this.getLecturesid().equals(other.getLecturesid()))
            && (this.getCommentcontent() == null ? other.getCommentcontent() == null : this.getCommentcontent().equals(other.getCommentcontent()))
            && (this.getConmmentdate() == null ? other.getConmmentdate() == null : this.getConmmentdate().equals(other.getConmmentdate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCommentid() == null) ? 0 : getCommentid().hashCode());
        result = prime * result + ((getUserid() == null) ? 0 : getUserid().hashCode());
        result = prime * result + ((getLecturesid() == null) ? 0 : getLecturesid().hashCode());
        result = prime * result + ((getCommentcontent() == null) ? 0 : getCommentcontent().hashCode());
        result = prime * result + ((getConmmentdate() == null) ? 0 : getConmmentdate().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", commentid=").append(commentid);
        sb.append(", userid=").append(userid);
        sb.append(", lecturesid=").append(lecturesid);
        sb.append(", commentcontent=").append(commentcontent);
        sb.append(", conmmentdate=").append(conmmentdate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}