package com.zym.dao;

import java.util.Date;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.zym.domain.Enroll;

public interface EnrollMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enroll
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long enrollid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enroll
     *
     * @mbggenerated
     */
    int insert(Enroll record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enroll
     *
     * @mbggenerated
     */
    int insertSelective(Enroll record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enroll
     *
     * @mbggenerated
     */
    Enroll selectByPrimaryKey(Long enrollid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enroll
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Enroll record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enroll
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Enroll record);
    List<Enroll> selectenrollList();
    Enroll selectenrollByUseridAndLecturesid( @Param("userid") long userid, @Param("lecturesid") int lecturesid);
    int selectcountenroll(@Param("lecturesid") int lecturesid);
    List<Enroll>  queryuserenrollBydate( @Param("userid") long userid, @Param("lecturestime") Date lecturestime);
    List<Enroll>    queryuserenrollByuserid( @Param("userid") long userid);
	List<Enroll> getEnrollByDate(Map<String, Object> map);
	  List<Enroll> queryuserenrollBylecturesid(@Param("lecturesid") int lecturesid);
	
}