package com.zym.domain;

import java.io.Serializable;

public class Classroom implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classroom.classroomid
     *
     * @mbggenerated
     */
    private Integer classroomid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classroom.classroomname
     *
     * @mbggenerated
     */
    private String classroomname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classroom.lat
     *
     * @mbggenerated
     */
    private String lat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classroom.lng
     *
     * @mbggenerated
     */
    private String lng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table classroom
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classroom.classroomid
     *
     * @return the value of classroom.classroomid
     *
     * @mbggenerated
     */
    public Integer getClassroomid() {
        return classroomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classroom.classroomid
     *
     * @param classroomid the value for classroom.classroomid
     *
     * @mbggenerated
     */
    public void setClassroomid(Integer classroomid) {
        this.classroomid = classroomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classroom.classroomname
     *
     * @return the value of classroom.classroomname
     *
     * @mbggenerated
     */
    public String getClassroomname() {
        return classroomname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classroom.classroomname
     *
     * @param classroomname the value for classroom.classroomname
     *
     * @mbggenerated
     */
    public void setClassroomname(String classroomname) {
        this.classroomname = classroomname == null ? null : classroomname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classroom.lat
     *
     * @return the value of classroom.lat
     *
     * @mbggenerated
     */
    public String getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classroom.lat
     *
     * @param lat the value for classroom.lat
     *
     * @mbggenerated
     */
    public void setLat(String lat) {
        this.lat = lat == null ? null : lat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classroom.lng
     *
     * @return the value of classroom.lng
     *
     * @mbggenerated
     */
    public String getLng() {
        return lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classroom.lng
     *
     * @param lng the value for classroom.lng
     *
     * @mbggenerated
     */
    public void setLng(String lng) {
        this.lng = lng == null ? null : lng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Classroom other = (Classroom) that;
        return (this.getClassroomid() == null ? other.getClassroomid() == null : this.getClassroomid().equals(other.getClassroomid()))
            && (this.getClassroomname() == null ? other.getClassroomname() == null : this.getClassroomname().equals(other.getClassroomname()))
            && (this.getLat() == null ? other.getLat() == null : this.getLat().equals(other.getLat()))
            && (this.getLng() == null ? other.getLng() == null : this.getLng().equals(other.getLng()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getClassroomid() == null) ? 0 : getClassroomid().hashCode());
        result = prime * result + ((getClassroomname() == null) ? 0 : getClassroomname().hashCode());
        result = prime * result + ((getLat() == null) ? 0 : getLat().hashCode());
        result = prime * result + ((getLng() == null) ? 0 : getLng().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", classroomid=").append(classroomid);
        sb.append(", classroomname=").append(classroomname);
        sb.append(", lat=").append(lat);
        sb.append(", lng=").append(lng);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}