package com.zym.domain;

import java.io.Serializable;

public class Colleges implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column colleges.collegesid
     *
     * @mbggenerated
     */
    private Integer collegesid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column colleges.collegesname
     *
     * @mbggenerated
     */
    private String collegesname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table colleges
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column colleges.collegesid
     *
     * @return the value of colleges.collegesid
     *
     * @mbggenerated
     */
    public Integer getCollegesid() {
        return collegesid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column colleges.collegesid
     *
     * @param collegesid the value for colleges.collegesid
     *
     * @mbggenerated
     */
    public void setCollegesid(Integer collegesid) {
        this.collegesid = collegesid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column colleges.collegesname
     *
     * @return the value of colleges.collegesname
     *
     * @mbggenerated
     */
    public String getCollegesname() {
        return collegesname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column colleges.collegesname
     *
     * @param collegesname the value for colleges.collegesname
     *
     * @mbggenerated
     */
    public void setCollegesname(String collegesname) {
        this.collegesname = collegesname == null ? null : collegesname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table colleges
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Colleges other = (Colleges) that;
        return (this.getCollegesid() == null ? other.getCollegesid() == null : this.getCollegesid().equals(other.getCollegesid()))
            && (this.getCollegesname() == null ? other.getCollegesname() == null : this.getCollegesname().equals(other.getCollegesname()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table colleges
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCollegesid() == null) ? 0 : getCollegesid().hashCode());
        result = prime * result + ((getCollegesname() == null) ? 0 : getCollegesname().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table colleges
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", collegesid=").append(collegesid);
        sb.append(", collegesname=").append(collegesname);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}