package com.zym.domain;

import java.io.Serializable;
import java.util.Date;

public class Enroll implements Serializable {
	private User user;
    public User getUser() {
		return user;
	}
    public Lectures getLectures() {
		return lectures;
	}

	public void setLectures(Lectures lectures) {
		this.lectures = lectures;
	}
	private Lectures lectures;
  
	public void setUser(User user) {
		this.user = user;
	}
	
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enroll.enrollid
     *
     * @mbggenerated
     */
	private Long enrollid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enroll.lecturesid
     *
     * @mbggenerated
     */
    private Integer lecturesid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enroll.userid
     *
     * @mbggenerated
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enroll.enrolltime
     *
     * @mbggenerated
     */
    private Date enrolltime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table enroll
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enroll.enrollid
     *
     * @return the value of enroll.enrollid
     *
     * @mbggenerated
     */
    public Long getEnrollid() {
        return enrollid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enroll.enrollid
     *
     * @param enrollid the value for enroll.enrollid
     *
     * @mbggenerated
     */
    public void setEnrollid(Long enrollid) {
        this.enrollid = enrollid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enroll.lecturesid
     *
     * @return the value of enroll.lecturesid
     *
     * @mbggenerated
     */
    public Integer getLecturesid() {
        return lecturesid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enroll.lecturesid
     *
     * @param lecturesid the value for enroll.lecturesid
     *
     * @mbggenerated
     */
    public void setLecturesid(Integer lecturesid) {
        this.lecturesid = lecturesid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enroll.userid
     *
     * @return the value of enroll.userid
     *
     * @mbggenerated
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enroll.userid
     *
     * @param userid the value for enroll.userid
     *
     * @mbggenerated
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enroll.enrolltime
     *
     * @return the value of enroll.enrolltime
     *
     * @mbggenerated
     */
    public Date getEnrolltime() {
        return enrolltime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enroll.enrolltime
     *
     * @param enrolltime the value for enroll.enrolltime
     *
     * @mbggenerated
     */
    public void setEnrolltime(Date enrolltime) {
        this.enrolltime = enrolltime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enroll
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Enroll other = (Enroll) that;
        return (this.getEnrollid() == null ? other.getEnrollid() == null : this.getEnrollid().equals(other.getEnrollid()))
            && (this.getLecturesid() == null ? other.getLecturesid() == null : this.getLecturesid().equals(other.getLecturesid()))
            && (this.getUserid() == null ? other.getUserid() == null : this.getUserid().equals(other.getUserid()))
            && (this.getEnrolltime() == null ? other.getEnrolltime() == null : this.getEnrolltime().equals(other.getEnrolltime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enroll
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getEnrollid() == null) ? 0 : getEnrollid().hashCode());
        result = prime * result + ((getLecturesid() == null) ? 0 : getLecturesid().hashCode());
        result = prime * result + ((getUserid() == null) ? 0 : getUserid().hashCode());
        result = prime * result + ((getEnrolltime() == null) ? 0 : getEnrolltime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enroll
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", enrollid=").append(enrollid);
        sb.append(", lecturesid=").append(lecturesid);
        sb.append(", userid=").append(userid);
        sb.append(", enrolltime=").append(enrolltime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}