package com.zym.domain;

import java.io.Serializable;
import java.util.Date;

public class Video implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.videoid
     *
     * @mbggenerated
     */
    private Integer videoid;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.videoname
     *
     * @mbggenerated
     */
    private String videoname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.videocontent
     *
     * @mbggenerated
     */
    private String videocontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.videourl
     *
     * @mbggenerated
     */
    private String videourl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.videopic
     *
     * @mbggenerated
     */
    private String videopic;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.addtime
     *
     * @mbggenerated
     */
    private Date addtime;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table video
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.videoid
     *
     * @return the value of video.videoid
     *
     * @mbggenerated
     */
    public Integer getVideoid() {
        return videoid;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.videoid
     *
     * @param videoid the value for video.videoid
     *
     * @mbggenerated
     */
    public void setVideoid(Integer videoid) {
        this.videoid = videoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.videoname
     *
     * @return the value of video.videoname
     *
     * @mbggenerated
     */
    public String getVideoname() {
        return videoname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.videoname
     *
     * @param videoname the value for video.videoname
     *
     * @mbggenerated
     */
    public void setVideoname(String videoname) {
        this.videoname = videoname == null ? null : videoname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.videocontent
     *
     * @return the value of video.videocontent
     *
     * @mbggenerated
     */
    public String getVideocontent() {
        return videocontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.videocontent
     *
     * @param videocontent the value for video.videocontent
     *
     * @mbggenerated
     */
    public void setVideocontent(String videocontent) {
        this.videocontent = videocontent == null ? null : videocontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.videourl
     *
     * @return the value of video.videourl
     *
     * @mbggenerated
     */
    public String getVideourl() {
        return videourl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.videourl
     *
     * @param videourl the value for video.videourl
     *
     * @mbggenerated
     */
    public void setVideourl(String videourl) {
        this.videourl = videourl == null ? null : videourl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.videopic
     *
     * @return the value of video.videopic
     *
     * @mbggenerated
     */
    public String getVideopic() {
        return videopic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.videopic
     *
     * @param videopic the value for video.videopic
     *
     * @mbggenerated
     */
    public void setVideopic(String videopic) {
        this.videopic = videopic == null ? null : videopic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.addtime
     *
     * @return the value of video.addtime
     *
     * @mbggenerated
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.addtime
     *
     * @param addtime the value for video.addtime
     *
     * @mbggenerated
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Video other = (Video) that;
        return (this.getVideoid() == null ? other.getVideoid() == null : this.getVideoid().equals(other.getVideoid()))
            && (this.getVideoname() == null ? other.getVideoname() == null : this.getVideoname().equals(other.getVideoname()))
            && (this.getVideocontent() == null ? other.getVideocontent() == null : this.getVideocontent().equals(other.getVideocontent()))
            && (this.getVideourl() == null ? other.getVideourl() == null : this.getVideourl().equals(other.getVideourl()))
            && (this.getVideopic() == null ? other.getVideopic() == null : this.getVideopic().equals(other.getVideopic()))
            && (this.getAddtime() == null ? other.getAddtime() == null : this.getAddtime().equals(other.getAddtime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getVideoid() == null) ? 0 : getVideoid().hashCode());
        result = prime * result + ((getVideoname() == null) ? 0 : getVideoname().hashCode());
        result = prime * result + ((getVideocontent() == null) ? 0 : getVideocontent().hashCode());
        result = prime * result + ((getVideourl() == null) ? 0 : getVideourl().hashCode());
        result = prime * result + ((getVideopic() == null) ? 0 : getVideopic().hashCode());
        result = prime * result + ((getAddtime() == null) ? 0 : getAddtime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", videoid=").append(videoid);
        sb.append(", videoname=").append(videoname);
        sb.append(", videocontent=").append(videocontent);
        sb.append(", videourl=").append(videourl);
        sb.append(", videopic=").append(videopic);
        sb.append(", addtime=").append(addtime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}