package com.zym.domain;

import java.io.Serializable;
import java.util.Date;

public class Collection implements Serializable {
	private User user;
    public User getUser() {
		return user;
	}
    public Lectures getLectures() {
		return lectures;
	}

	public void setLectures(Lectures lectures) {
		this.lectures = lectures;
	}
	private Lectures lectures;
  
	public void setUser(User user) {
		this.user = user;
	}
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection.collectionid
     *
     * @mbggenerated
     */
    private Integer collectionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection.userid
     *
     * @mbggenerated
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection.lecturesid
     *
     * @mbggenerated
     */
    private Integer lecturesid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection.collectiontime
     *
     * @mbggenerated
     */
    private Date collectiontime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table collection
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection.collectionid
     *
     * @return the value of collection.collectionid
     *
     * @mbggenerated
     */
    public Integer getCollectionid() {
        return collectionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection.collectionid
     *
     * @param collectionid the value for collection.collectionid
     *
     * @mbggenerated
     */
    public void setCollectionid(Integer collectionid) {
        this.collectionid = collectionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection.userid
     *
     * @return the value of collection.userid
     *
     * @mbggenerated
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection.userid
     *
     * @param userid the value for collection.userid
     *
     * @mbggenerated
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection.lecturesid
     *
     * @return the value of collection.lecturesid
     *
     * @mbggenerated
     */
    public Integer getLecturesid() {
        return lecturesid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection.lecturesid
     *
     * @param lecturesid the value for collection.lecturesid
     *
     * @mbggenerated
     */
    public void setLecturesid(Integer lecturesid) {
        this.lecturesid = lecturesid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection.collectiontime
     *
     * @return the value of collection.collectiontime
     *
     * @mbggenerated
     */
    public Date getCollectiontime() {
        return collectiontime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection.collectiontime
     *
     * @param collectiontime the value for collection.collectiontime
     *
     * @mbggenerated
     */
    public void setCollectiontime(Date collectiontime) {
        this.collectiontime = collectiontime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Collection other = (Collection) that;
        return (this.getCollectionid() == null ? other.getCollectionid() == null : this.getCollectionid().equals(other.getCollectionid()))
            && (this.getUserid() == null ? other.getUserid() == null : this.getUserid().equals(other.getUserid()))
            && (this.getLecturesid() == null ? other.getLecturesid() == null : this.getLecturesid().equals(other.getLecturesid()))
            && (this.getCollectiontime() == null ? other.getCollectiontime() == null : this.getCollectiontime().equals(other.getCollectiontime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCollectionid() == null) ? 0 : getCollectionid().hashCode());
        result = prime * result + ((getUserid() == null) ? 0 : getUserid().hashCode());
        result = prime * result + ((getLecturesid() == null) ? 0 : getLecturesid().hashCode());
        result = prime * result + ((getCollectiontime() == null) ? 0 : getCollectiontime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", collectionid=").append(collectionid);
        sb.append(", userid=").append(userid);
        sb.append(", lecturesid=").append(lecturesid);
        sb.append(", collectiontime=").append(collectiontime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}